### ISSUE TITLE
Import PlanningAlerts emails into CiviCRM

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#164]
So @equivalentideas can do a mail out to them.

**Comment by henare** [comment]
First step was to extract email addresses from PlanningAlerts. We now have an easy way to do this via the admin backend: https://github.com/openaustralia/planningalerts-app/issues/599

The next step is importing those (currently 20,000) email addresses into CiviCRM. The CiviCRM importer just seems to hang and freezes the whole website when you try to do that so you need to split them into smaller chunks.

I've found doing 2000 at a time seems manageable (i.e. it sits there for a couple of minutes but does eventually complete successfully).

Note that the importer's duplicate matching must be set to "fill" or "update" despite being much slower than "skip" as it does not apply the tag to existing contacts.

**Comment by henare** [comment]
That seemed to work but it was very slow to do :(

**Comment by equivalentideas** [comment]
Here's a script for breaking the massive 50000 line emails.txt file you get out of PlanningAlerts into separate files you can import into civicrm for each 2000 addresses https://gist.github.com/equivalentideas/070e7be07985cabbad5334fb6b7f5bf2

**Comment by henare** [comment]
@equivalentideas you could also use the built-in [`split`](https://en.wikipedia.org/wiki/Split_(Unix)) command :banana:
