### ISSUE TITLE
The process to unsubscribe from emails is horrible

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#166]
The citizen has to fill out a very badly designed form to unsubscribe, the submit button is barely visible (#185):

![screen shot 2015-01-06 at 1 04 36 pm](https://cloud.githubusercontent.com/assets/1239550/5625222/e5ee6ca0-95ca-11e4-900b-30ebf5225737.jpg)

Yuck. If someone wants to unsubscribe we should do it automatically as is (Gandalf willing) increasingly the norm.

**Comment by henare** [comment]
I've asked on the CiviCRM forum if we can remove the confirmation step entirely: https://forum.civicrm.org/index.php/topic,35416.0.html

**Comment by equivalentideas** [comment]
Here's some thoughts from Mailchimp on this http://blog.mailchimp.com/one-click-accidental-unsubscribes-fix/

**Comment by henare** [comment]
A lovely person on the forum pointed out that this is a relatively new "feature" (not a bug!).

I've raised an issue to at least make it configurable (because CiviCRM needs more configuration options!): https://issues.civicrm.org/jira/browse/CRM-15825

**Comment by jamezpolley** [comment]
we don't use civicrm any more.
