### ISSUE TITLE
Thank the people who responded to our past donors survey

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#168]
These people have been very helpful and deserve out thanks. We can also update them with what we've learnt and how we're planning to use it.

**Comment by henare** [comment]
Now that the blog post is done (#169) would this be a good time to do this?

**Comment by equivalentideas** [comment]
1. Thanks them for the donation!

  > Thank you for the donation, it will go straight to the development of our projects.
2. Ask if they're aware of another relevant project (e.g. OpenAustralia.org alerts if they're a Right To Know or They Vote For You user), or ask if they have any feedback.
3. Let them know they can contact us any time
   > Please don't hesitate to reach out if you have any ideas or questions.


Be nice, these people are awesome. We want to give them more ways to get use from our work and to share it with others.

**Comment by equivalentideas** [comment]
done
