### ISSUE TITLE
Conduct survey with people who receive PlanningAlerts alerts

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#170]
PlanningAlerts is the biggest OAF project in terms of people who use it and in terms of the number of people who make donations to OAF.

Information about:
- who the people using PlanningAlerts are,
- what they know about OAF and how PlanningAlerts is run/maintained, and
- if and why they donate to organisations,

—will help us design our donations flow to better support people who want to support PlanningAlerts and make the case for why they should support it.

This survey was similar to the one conducted with past donors to OAF #167 .

Questions:
- Roughly, how old are you? (Under 20, 20s, 30s, 40s, 50s, 60s, 70s, Above 80)
- What is your occupation?
- Do you regularly donate money to organisations or projects?
- Do you use PlanningAlerts in your job?
- Did you know that PlanningAlerts is run by an independent charity, the OpenAustralia Foundation?
- Why is PlanningAlerts important to you?
- Would you be happy to have a brief chat to help us learn more?

**Comment by equivalentideas** [comment]
We sent off the survey (using google forms) to about 23,000 people who are signed up for PlanningAlerts and 24 hours later we're received 1000 filled out surveys.

**Comment by henare** [comment]
Some useful questions when doing phone interviews:

* How did you discover PlanningAlerts?
* How long have you been using it?
* What do you use it for? [Ask them to tell specific stories]
* Have you had problems getting information about planning in your area?
* What charities do you support and why?
* Any other feedback or questions you have?

**Comment by jamezpolley** [comment]
Sounds like this has been done.
