### ISSUE TITLE
OA.org subscriber regular donation request

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#171]
- [x] #172 Import list of OA.org subscribers into CiviCRM
- [x] #144 Stripe
- [x] Write email
- [x] Send email

**Comment by equivalentideas** [comment]
Draft email:

Hi, Henare here from the OpenAustralia Foundation, the people behind OpenAustralia.org .

Firstly, thanks for being part of the community making OpenAustralia.org a success. The project is entering it’s 8th year and thousands of people use it stay informed about what's being said in Parliament.

Every year we work to maintain, support and expand the project. You might have noticed that we've recently added the voting history of MPs (thanks to our new project They Vote For You). Parliament will be back soon and your alerts will be coming through.

Do you find the alerts from OpenAustralia.org useful?

If you do, we would greatly appreciate it if you would chip in to support the project with a monthly, tax deductible donation to the OpenAustralia Foundation.

**https://www.openaustraliafoundation.org.au/donate/**

The OpenAustralia Foundation is an independent, non-partisan charity, powered by contributions from people like you who use our work. Your support enables us to build and maintain projects that inform and empower people with real information about our society and government.

If you have any feedback or questions about Openaustralia.org or the OpenAustralia Foundation, please reply to get in touch. We're always keen to hear ideas and connect with the people using our projects.

Best wishes,

Henare

**Comment by equivalentideas** [comment]
Scheduled to go tomorrow 10:30 AM

**Comment by kat** [comment]
Hi Luke

I'm just having a quick look at this for grammar, mostly. I have noticed a couple of little errors and also have some suggestions for you. 

here is a version incorporating bugs and other changes which I think improve the flow slightly. below that is more explanation and some other suggestions. I will leave it to you which changes you'd like to incorporate in the mailout, or not. Good luck!

Hi, Henare here from the OpenAustralia Foundation. I'm one of the people behind OpenAustralia.org.

Firstly, I'd like to thank you for being part of the OpenAustralia.org success story. Entering its 8th year, thousands of people use it to stay informed about what's being said in Parliament.

Every year we work to maintain, support and expand on this vital project. You might have noticed that we've recently added the voting history of MPs (thanks to our new project They Vote For You). 

Parliament will be back soon and your alerts will be coming through.

Do you find the alerts from OpenAustralia.org useful?

If you do, we would greatly appreciate it if you would chip in to support the project with a monthly, tax deductible donation to the OpenAustralia Foundation.

**https://www.openaustraliafoundation.org.au/donate/**

The OpenAustralia Foundation is an independent, non-partisan charity, and we're powered by contributions from people like you who use our work. Your support enables us to build and maintain projects that inform and empower people with real information about our society and government.

If **you** have any feedback or questions about Openaustralia.org or the OpenAustralia Foundation, please reply to get in touch. We're always keen to hear your ideas and connect with the people using our projects.

Best wishes,

Henare

----------
So the important bits are the BUGs, which I've also outlined below in case you'd rather just fix mistakes.
BUG: @henare  is not yet equivalent to a group of people, even if sometimes it seems like it  :-)
so he can't say

Hi, Henare here from the OpenAustralia Foundation, the people behind OpenAustralia.org .

do you mean '**one** of the people behind'? Also the full stop at the end has a space before it. 

Comment: I'm finding a first person 'uncanny valley' I'm not sure if Henare is speaking directly to me or not in this sentence, also it doesn't scan that well.
Suggestion: "I'm one of the people behind..." may be better. Maybe?
and  related is "Firstly, thanks for being part of the community making OpenAustralia.org a success "
'thanks' after a personal direct greeting seems too casual. 
Perhaps "Firstly, I'd like to thank you' ? emphasises the 'you' here. 

BUG: the following sentence needs and extra word - maybe 'to' as below.

The project is entering it’s 8th year and thousands of people use it **to** stay informed about what's being said in Parliament.

**Comment by equivalentideas** [comment]
Thanks for that Kat, I'm incorporating this stuff in :)

**Comment by equivalentideas** [comment]
Hi, Henare here from the OpenAustralia Foundation, the charity behind OpenAustralia.org.

Firstly, I’d like to thanks you for being part of the community making OpenAustralia.org a success. The project is entering it’s 8th year and thousands of people use it to stay informed about what’s being said in Parliament.

Every year we work to maintain, support and expand this vital project. You might have noticed that we’ve recently added the voting history of MPs (thanks to our new project They Vote For You). Parliament will be back soon and your alerts will be coming through.

**Do you find the alerts from OpenAustralia.org useful?**

If you do, we would greatly appreciate it if you would chip in to support the project with a monthly, tax deductible donation to the OpenAustralia Foundation.

**https://www.openaustraliafoundation.org.au/donate/**

The OpenAustralia Foundation is an independent, non-partisan charity, powered by contributions from people like you who use our work. Your support enables us to build and maintain projects that inform and empower people with real information about our society and government.

If you have any feedback or questions about Openaustralia.org or the OpenAustralia Foundation, please reply to get in touch. We’re always keen to hear ideas and connect with the people using our projects.

Best wishes,

Henare Degan
Director, OpenAustralia Foundation

**Comment by equivalentideas** [comment]
Sent
