### ISSUE TITLE
Launch "This month in civic tech" email newsletter

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#173]
This newsletter is a way to engage and support people interested in civic tech projects like those run by the OpenAustralia Foundation.

It should be published shortly before the [OAF pub meetup](http://www.meetup.com/OpenAustralia-Foundation/) so anything arising of interest can be discussed there.

It should be succinct and use headings/links to make any extended content scannable. People are smart and busy remember.

What should the scope of the newsletter be?

* Support promising projects?
* update people on OAF projects/events
* discuss interesting examples?
* link to relevant articles/videos etc. ?
* all of the above?

**Comment by equivalentideas** [comment]
As soon as we have an idea of what this will be about, let's make a signup for and send it out via twitter, the oa email list and do a blog post so people can sign up while we're getting things together.

**Comment by equivalentideas** [comment]
A couple of examples of similar concepts:

* The NiemanLab excellent/popular daly/weekly newsletter with links on the “future-of-news” http://www.niemanlab.org/subscribe/
* Web Directions weekly newsletter feature design, development and ideas links, sometime around a topic, and often featuring promotions of WD upcoming events. There was a big applause for the newsletter at the Web Directions 2014 conference in Sydney: webdirections.org

**Comment by equivalentideas** [comment]
I think the Thursday morning before the Pub Meet would be a good time to send out the email. That gives people coming the pub meet a few days and a weekend to find some time for a read, and for others it's a nice relaxed later in the week time so that it's in people minds for the weekend. Web Directions send out their weekly email on a Friday for example.

If that's when we want to send it out, then the first one will be the Thursday, 19th of February.

**Comment by henare** [comment]
>If that's when we want to send it out, then the first one will be the Thursday, 19th of February.

:+1: SGTM!

**Comment by henare** [comment]
TODO as discussed with @equivalentideas:

- [x] Decide on tool to collect and compile the newsletter: a new GitHub repo
- [ ] Create GitHub repo
- [ ] Develop design principles for and structure of the newsletter (document in repo)
- [ ] Set up MailChimp account and basic template
- [ ] Sign up people on the Google Group and tell them about it

**Comment by equivalentideas** [comment]
For the collection of links for the newsletter, here's the plan @henare and I are thinking:

Have a /newsletter repo, people can create issues with links they'd like to be included and we can then close them once added.

Nice things about having it in a repo:

* we have clear space for information about the newsletter such as contributing guidelines
* people can get involved if they like to let us know about things that should be included
* it's all super transparent and backed up.

**Comment by equivalentideas** [comment]
Here's the repo https://github.com/openaustralia/newsletter

**Comment by equivalentideas** [comment]
This is now all being handled on the openaustralia/newsletter repo. I'm closing this ticket.
