### ISSUE TITLE
Make the regular donations feature work 'better'

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#174]
Presently there are a lot of unknowns in the regular donation process:

* what happens if someone wants to cancel?
* what happens if a card can't process suddenly?
* do we email people when we draw funds?

As part of the move to Stripe ( #178 ) we should get this working properly and make it a nice experience for these kind people.

**Comment by henare** [comment]
I'm going to test things with Stripe to see how it all works and fix any things that don't look right along the way.

**Comment by henare** [comment]
Extracted #182.
