### ISSUE TITLE
Conduct short survey to get feedback and ideas from Right To Know users

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#175]
- Make contact with users of Right To Know
- let them know about the OpenAustralia Foundation (and mention that we're open for donations)
- find out how they're going with the application, do they have feedback? Ideas? What do they think is successful? What could use work?

**Comment by henare** [comment]
We could ask them about https://github.com/openaustralia/righttoknow/issues/366

**Comment by brfairless** [comment]
We say this on RTK:
> After you sign up to Right to Know, we will only send you emails relating to a request you made, an email alert that you have signed up for, or for other reasons that you specifically authorise.

I'm not sure if any of our users would have issues being contacted by us for a survey. Could we use the green bar to redirect them to a survey, which doesn't break the above?

**Comment by henare** [comment]
Well spotted Ben - we should change that. We've contacted people in the past and will continue to do so.

**Comment by brfairless** [comment]
It's now been changed. So this should be OK to go
