### ISSUE TITLE
Identify groups to introduce to OAF projects

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#176]
One observation we made from talking with people who have donated to OAF ( #167 ) is that a number of them have had direct contact with the organisation, or have been directly introduced to a project by someone they know.

Many of these donors were also passionate expert or 'power users' within there area: FOI or local planning for example.

There are many social groups and organisations working around issues such as local planning and development, democratic engagement, FOI and Open Data/Gov, civic innovation. OAF projects aid the members of these groups in doing the work they already have a strong passion for. In turn these people see the social value in the projects, and see value for themselves themselves, and are more likely to donate to support their development and maintenance.

To introduce members of these groups to the specific projects that could help them we could speak and there events and be featured in their community newsletters/communications.

The first step is to start identifying groups to contact.

## OpenAustralia.org and They Vote For You
Student politics groups:

* [Sydney University Liberal Club ](http://sulc.com.au/) - alexdore[AT]sulc.com.au [EMAILED]
* [Sydney University Labor Club ](http://www.usu.edu.au/Clubs-Societies/Our-clubs-societies/Political/Labor-Club.aspx) - Chloe Smith laborclub.usyd@gmail.com [CALLED - left a message]
* [Sydney University Greens on Campus ](https://www.facebook.com/usyd.greens) Contact details??
## PlanningAlerts

Residents associations:

* [Friends of Erskineville ](http://www.erskinevillevillage.org/) [VISITED - [notes ](https://docs.google.com/a/oaf.org.au/document/d/1dYPi0fr1clbyDmkIqJjNiZKXu1O3kW3QPalohimPYQU/edit)]
* [Marrickville Heritage Society ](http://marrickville-heritage.blogspot.com.au/) heritagesociety@optusnet.com.au [EMAILED]
* [Alexandria Residents Action Group ](http://arag.org.au/) info@arag.org.au [EMAILED]

**Comment by henare** [comment]
Here's an excellent list of resident action groups around inner-Sydney: http://www.cityofsydney.nsw.gov.au/community/participation/community-groups

**Comment by henare** [comment]
To test this I think it might be an idea to pick a few groups, try and present to them and see how it goes and what response we get.

We could pick a few:

* Resident action groups (PlanningAlerts)
* Student politics groups or politics related groups on meetup.com (OpenAustralia.org/They Vote For You)
* Transparency groups - TI? Recordkeeping Roundtable? meetup.com? (Right To Know)

**Comment by equivalentideas** [comment]
Great idea Henare. For PlanningAlerts, maybe we could pick groups in our local areas to start with?

**Comment by henare** [comment]
Yeah, see the list above.

**Comment by henare** [comment]
I'm going to try and email 6 different groups today to start a conversation about visiting them an introducing a relevant project to them in person.

**Comment by equivalentideas** [comment]
Could be good to keep a list of who we've contacted in a spreadsheet.
