### ISSUE TITLE
When using Stripe the person donating is asked for heaps of pointless billing information

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#178]
Extracted from #144.

When using the Stripe payment processor the person is asked for all this extra "billing information", including their name (again!) and all their address details.

As far as I know, we don't _need_ these address details so it would be great not to include them in the form.

**Comment by henare** [comment]
@equivalentideas and I are planning to do some Javascript that will hide this part of the form until the person clicks a "Continue" button.

I'll work out how to get JS into our theme and then Luke will write the Javascript to make it work.

**Comment by equivalentideas** [comment]
Here's a good example of the progressive disclosure design https://www.pittsburghfoodbank.org/donate/

**Comment by henare** [comment]
>I'll work out how to get JS into our theme and then Luke will write the Javascript to make it work.

Already done: https://github.com/openaustralia/oaf-thematic/compare/openaustralia:master...custom.js

**Comment by henare** [comment]
Since Stripe is far more preferable to PayPal we've switched to it for all our donation pages. We'll still do this ticket though.

**Comment by equivalentideas** [comment]
This has been merged as is running live.

**Comment by henare** [comment]
Reopened because it's still asking for all this address information:

https://www.openaustraliafoundation.org.au/donate/planningalerts/

![selection_001](https://cloud.githubusercontent.com/assets/48945/17355408/a7a691aa-5993-11e6-8f38-59ef8eb6280e.png)

I was made aware of this because someone emailed us saying they wanted to donate but we asked for too much extra info (fair enough!).

**Comment by jamezpolley** [comment]
doesn't happenw ith donorbox
