### ISSUE TITLE
Set up better tracking of donation email results

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#187]
Keep track of the responses to donation request emails so we can quickly compare the results and use the feedback to adjust our approach.

**Comment by henare** [comment]
What does this mean?

**Comment by equivalentideas** [comment]
See above.

**Comment by henare** [comment]
A simple way could be a Google Doc for each mailing?

**Comment by equivalentideas** [comment]
making spreadsheet for this.
