### ISSUE TITLE
Donation thanks guide

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#188]

**Comment by equivalentideas** [comment]
1. Thanks them for the donation!

  > Thank you for the donation, it will go straight to the development of our projects.
2. Ask if they're aware of another relevant project (e.g. OpenAustralia.org alerts if they're a Right To Know or They Vote For You user), or ask if they have any feedback.
3. Let them know they can contact us any time

  > Please don't hesitate to reach out if you have any ideas or questions.


Be nice, these people are smart and awesome. We want to give them more ways to get use from our work and to share it with others.

**Comment by equivalentideas** [comment]
Moved this over to google docs. Working template is there https://docs.google.com/a/oaf.org.au/document/d/1rSJJj37dvGkAcAXHpsPOiNgtNJy1ss1nH0zOWgcBRpw/edit

**Comment by henare** [comment]
Looks good!

**Comment by equivalentideas** [comment]
Reopened as we're reworking the template.

**Comment by kat** [comment]
Unless you want to update the template with any of the thoughts from [this research](https://docs.google.com/a/oaf.org.au/document/d/1zCv6lgQdGEaOvKVLUojszKl1Ir85BQyjKkSmew8aKzk/edit)
or my attempt at [a nice thank you](https://docs.google.com/a/oaf.org.au/document/d/1vdTGOVF8dKbPSxgAl6lZWBXOinH93jNFl_9GBA8bt2E/edit) this can stay closed. I was really thinking ahead about the end of year prep/donation call, which can be new issues.

**Comment by equivalentideas** [comment]
Just noting some of the thinking behind the email that doesn't seem to be noted anywhere. 

Aside from the stuff above, we also added a bit to the template to try and continue the interaction with the person donating.

We thought that people who've had this happy injection from donating are perfect to prompt to share there experience with others. They almost certainly have family and friends who would be interested in the projects, and are the type of people who donation. They may well have some story of success with one of the projects to share with their friends, and that kind of direct introduction seems to help people get into the projects and donate. See stuff under the heading 'Passionate and knowledgeable in their area of focus' in [donations research blog post](https://www.openaustraliafoundation.org.au/2015/01/16/getting-to-know-you/). This prompt is in the PS section, as BJ from Getup told me that after the subject the PS section is the most read part of an email.

We also thought to find out more about how these people discovered the project because they likely have achieved some democratic success with the projects. We might learn something interesting about the projects, and deepen the connection with this lovely person who has donated.

**Comment by equivalentideas** [comment]
Following up chat discussion with @kat about thanking people who've donated.

I think there are a few main questions:

## How should we thank people who sign up to regular donations?

I think we should thank them with an email when they first register, and then an annual thanks with their receipt before the end of the financial year.

## How should we record that we've thanked people?

I've just noticed the 'Thank-you sent' column in the contributions dashboard in civicrm. This seems like a pretty good place to keep track. It'll only take me a sec to fill in the column for the few this year. I'll do that now.

## How should we thank people who've already donated this year?

There are only 3 or 4 people who haven't been thanked. @kat did you want to email them or are you happy for me to do it?

## Who should be responsible for thanking people?

I'm not sure about this.

We could make one person responsible for this and then anyone can step in if they want to personally thank someone they had contact with?

@kat and @henare have I missed anything with this? What do you think about this stuff above?

**Comment by henare** [comment]
:+1:

**Comment by kat** [comment]
:+1:  go for it @equivalentideas
