### ISSUE TITLE
add subscribe widget to blog

### ISSUE THREAD

**Issue by kat** [openaustralia/oaf#191]
Add widget to give an option to sign up to get alerts when there's a blog post.
At the moment, we don't pick up regular followers to the blog even after a big spike of interest on a particular post.

**Comment by equivalentideas** [comment]
nice

**Comment by henare** [comment]
:+1:

**Comment by equivalentideas** [comment]
This has been done for a while, when we wrapped up the newsletter and changed it to just send out our blog posts.

![screen shot 2017-03-16 at 3 59 12 pm](https://cloud.githubusercontent.com/assets/1239550/23982449/985b89ec-0a61-11e7-85b8-821fdc70dea6.png)
