### ISSUE TITLE
post to twitter/ automatically when there's a new blog post

### ISSUE THREAD

**Issue by kat** [openaustralia/oaf#192]
something about sharing ...

**Comment by henare** [comment]
Blog posts happen so infrequently that I think something that does this automatically in unnecessary. 

Furthermore the automatically generated Tweets are always terrible (cf. Facebook auto posts to Twitter) since the medium is so different.

Thoughts?

**Comment by henare** [comment]
I'm closing this because of that comment :point_up: reopen if you disagree.
