### ISSUE TITLE
put google analytics traffic codes on civiCRM links

### ISSUE THREAD

**Issue by kat** [openaustralia/oaf#194]
so we can follow traffic coming to oaf.org.au or elsewhere through a civi mailout

**Comment by henare** [comment]
Since the links come via CiviCRM's click tracking I thought we'd be able to see this in Analytics but apparently not.

In this case I think that means we need to remember to manually add them when we send a mailout.

If that's true then is there as task this issue covers or should it be closed?

**Comment by jamezpolley** [comment]
we don't use civicrm. donorbox handles this.
