### ISSUE TITLE
Blogpost about mysociety TICTec conference

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/oaf#201]
@equivalentideas it would be great if you could write a blog post while things are still fresh in your mind about your experiences at the TICTec conference.

It doesn't have to be long at all - just something that links to the conference program, videos when they go up and describes your overall impression and a couple of things you learned.

You could also mention some of the people you met outside the conference too.

**Comment by equivalentideas** [comment]
A lovely idea I'll do that this week.

**Comment by mlandauer** [comment]
@equivalentideas don't forget to do this while things are still fresh in your mind ;-)

**Comment by equivalentideas** [comment]
working on it as we speak :)

**Comment by mlandauer** [comment]
nice one

**Comment by henare** [comment]
https://www.openaustraliafoundation.org.au/2015/04/08/the-impacts-of-civic-technology-conference-2015/

I found it really interesting, thanks @equivalentideas.
