### ISSUE TITLE
Blog post for Right To Know users about new mobile design

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#202]
We've just [deployed big changes](https://github.com/openaustralia/righttoknow/pull/452) to the front end of Right To Know that will effect people who use the site on mobile devices.

@henare [suggested](https://github.com/openaustralia/righttoknow/pull/452#issuecomment-88375397) a blog post announcing the changes.

**Comment by equivalentideas** [comment]
Questions to briefly answer in this post:

* What is good about this for me/why have you done this?
* What is the change?
* What can I do if I see problems?

**Comment by equivalentideas** [comment]
Published https://www.openaustraliafoundation.org.au/2015/04/02/a-better-right-to-know-on-your-phone/

**Comment by mlandauer** [comment]
@equivalentideas very nice post. Explains really clearly why this will helps people. Awesome ;-)

**Comment by equivalentideas** [comment]
Thanks @mlandauer , still trying to hit those four principles written down in front of me ;)
