### ISSUE TITLE
Blog about ACT on Right to Know

### ISSUE THREAD

**Issue by brfairless** [openaustralia/oaf#203]
I've started a draft in Wordpress, however it would be good to have someone look it over before it gets published :)

**Comment by equivalentideas** [comment]
Nice one. I'm not sure where we're at with announcing, so I recon hold off publishing till @henare can have a look—in my mind he had a plan for this stuff :)

**Comment by brfairless** [comment]
When I spoke with @henare last week he was keen to announce as we had successful requests. I'm just not sure on the wording of the blog post however.

**Comment by equivalentideas** [comment]
Nice one!

**Comment by henare** [comment]
@brfairless the blog post looks good, thanks! I've got a few ideas below but once you're happy with it please go ahead and publish it.

How about adding something about there already being a successful request?

You also mentioned that you found the process in the ACT good. Maybe we could also include something about that and how we hope that pattern continues ;)

Including an image is always a good idea. If you can't think of anything a CC-licensed photo of Canberra maybe?

**Comment by henare** [comment]
I'll finish this off so we can publish it this morning.

**Comment by henare** [comment]
:postbox: https://www.openaustraliafoundation.org.au/2015/04/13/right-to-know-is-now-in-the-act/
