### ISSUE TITLE
Stripe recurring donations not showing up in CiviCRM

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#205]
Extracted from #200.

We have webhooks set up in Stripe that post the payment back to CiviCRM but it looks like CiviCRM isn't picking them up. I was sure we tested this when it was reconfigured back in January but I guess we either didn't do a good enough job or something has once again broken in the mean time.

I just did a cursory check and noticed that the CiviCRM Stripe plugin said it needs a newer version of the Stripe API than we had configured. I've changed this but I haven't tested it works and we'll need to put more work into thoroughly testing it.

**Comment by jamezpolley** [comment]
we don't use civicrm any more.
