### ISSUE TITLE
Make front page sentence about people, not data

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#206]
The sentence we have on the front page of oaf.org.au was recently used by Ignite to summarise what we do and it struck me as not emphasising what we now see as the important part of our work

> We build tools to simplify the discovery and use of public data and we share them for free.

It talks about data whereas we like to talk about people, e.g. _do what is best for the citizen._

I think we'd all like to see the site get a general overhaul but this seems like a good low hanging fruit that we could do now.

**Comment by jamezpolley** [comment]
https://www.oaf.org.au/?customize_changeset_uuid=b665fcb6-dbaf-49ce-8ea5-df73ced2636d

@mlandauer @kat @katska Could you take a look at this preview?

**Comment by jamezpolley** [comment]
I've drafted a change that uses wording based on our Mission to replace this.

I've also changed "View Projects" to "View our Tools" to be consistent with "the tools they need".

Unless I hear otherwise I'll push this live in a week.

**Comment by jamezpolley** [comment]
Change published.

Page now says:
> The OpenAustralia Foundation
>
>Giving all Australians the tools they need to effect the change they want.
