### ISSUE TITLE
May Sydney Pub Meet

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#207]
For the first time ever I won't be able to make the pub meet. Oh no! :smiley: 

So I thought I'd document here what needs to be done and ask for a volunteer.

- [x] Book function at The Woolpack Hotel (already done in Henare's name)
- [x] Change organiser for May meetup to the volunteer
- [x] Announce on Meetup.com (and answer any comments people post on the event)
- [x] A few Tweets to promote it
- [x] On the night arrive early, greet everyone as the arrive throughout the evening and give first timers a run down of how the evening works
- [x] After the event fill in the "Stay in touch!" mail from Meetup.com where it asks how many people came, etc. so we can always go back and check the statistics if we need to
- [x] Have fun :tada: 

Who's up for it? @mlandauer @kat @equivalentideas

**Comment by henare** [comment]
Any takers @mlandauer @kat @equivalentideas? I need to change the organiser.

**Comment by equivalentideas** [comment]
It'll be May 26th? I'm up for it.

**Comment by henare** [comment]
@equivalentideas my hero, you've got it.

**Comment by equivalentideas** [comment]
Done http://www.meetup.com/OpenAustralia-Foundation/events/221490539/

**Comment by henare** [comment]
Nice one. Thanks @equivalentideas. I'm especially glad you got that last item in the list done :)
