### ISSUE TITLE
EOFY Donations appeal

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#208]
This month we plan to email out a call for donations to all the users of OpenAustralia projects. 

We're thinking:

* 2 emails, one early next week, one later in the month
* Sending slightly different emails to the users of the different projects. This is because we know many people are passionate about the project they use, but don't know or care much about our other projects. Many people are passionate about the core mission of the foundation, without being passionate about all our projects. We can frame this as a way for them to give back and help sustain the thing they love/find useful. We'll try and reuse content as much as possible to reduce time cost.

We're thinking that the content of the emails will be a concise review of all the awesome things that have happened this year on their project or just what's important about the project, and a strong statement of why they should support us.

Matthew did a big review of the last year in a recent email, we can draw on that for the content.

Here's a nice concise example from Wikimedia:

> Dear Luke,

> Thank you for helping keep Wikipedia online and ad-free. It's been a year since we've asked. This is your [annual reminder](https://donate.wikimedia.org).

> If all our past donors simply gave again today, we wouldn't have to worry about fundraising for the rest of the year. Please help us get back to improving Wikipedia.

> We are the small non-profit that runs the #5 website in the world. We have only 175 staff but serve 500 million users, and have costs like any other top site: servers, power, programs, and people.

> Wikipedia is something special. It is like a library or a public park. It is like a temple for the mind, a place we can all go to think and learn.

> To protect our independence, we'll never run ads. We take no government funds. We survive on donations from our readers. Now is the time we ask.

> [If Wikipedia is useful to you, please take one minute to give $10, $20, $50 or whatever you can to keep it online and ad-free another year](https://donate.wikimedia.org).

> https://donate.wikimedia.org

> Thanks,
> Jimmy Wales
> Wikipedia Founder

We're also thinking this kind of personal appeal style works well and them email should come from one of the directors and possibly have a photo of them.

As always, I think a very simple email design works best rather than the fancier template ones used in last years donations appeal.

**Comment by henare** [comment]
All sounds good to me.

>As always, I think a very simple email design works best rather than the fancier template ones used in last years donations appeal.

What makes you say that? Our donations appeal last year was quite successful so I think we need to carefully consider this.

**Comment by equivalentideas** [comment]
I remember when we looked at the conversion on those emails we didn't think it was particularly good—about the same as the fairly unsuccessful email to openaustralia users in January.

The survey emails in January had much higher conversion, which were just text, but they weren't asking people for money so I can see how it's a bit different. I could go either way on the design, use what we had last year or strip back, whatever is simplest for us and is going to be effective. We could even design something new if we think its going to help, just has to be worth the time.

**Comment by equivalentideas** [comment]
> Sending slightly different emails to the users of the different projects

Thinking a bit more about this, I think we could prioritise PlanningAlerts and RightToKnow and maybe do a general OAF one for They Vote For You, OpenAustralia.org.au and ElectionLeaflets. This is because those two projects have users who've donated more in the past that the others and are a bit more specialist.

Based on the previous low response we've had from OpenAustralia users, and that They Vote For You is quite new (smaller numbers) and ElectionLeaflets has been very quite, I don't think it's going to be worth the time to write and produce individual emails for those projects.

So I think we produce a version for PlanningAlerts, on for Right To Know and a general OAF one.

Do we want to email morph users?

**Comment by henare** [comment]
>So I think we produce a version for PlanningAlerts, on for Right To Know and a general OAF one.

Sounds like a good idea to me.

>Do we want to email morph users?

Yeah I think we should. However it's not so important that we email by the end of the financial year since most Morph.io users won't get the DGR benefit as they're not in Australia.

**Comment by equivalentideas** [comment]
We'll need to important the latest subscribers from the different projects into civi. It would be good to start with PlanningAlerts as that's the first email we've got prepared. @henare could I rope you in to help with that?

**Comment by equivalentideas** [comment]
As I understand it we're all happy with the PlanningAlerts email text. I think we send that one as soon as possible and then move onto text for the Right To Know email and general OpenAustralia Foundation one.

## Subject line for the PlanningAlerts email

After looking at a few resources http://blog.mailchimp.com/subject-line-data-choose-your-words-wisely/ and http://kb.mailchimp.com/delivery/deliverability-research/write-effective-subject-lines

> Thank you for another great year of PlanningAlerts

Because:

* anything about donations seems to have a negative impact on open rates,
* "Thank you" apparently has a positive effect and it's very distinct from their usual alert emails
* 'another great year of PlanningAlerts' sets up the story of the content and lines up that there's information about something in here which hopefully will entice people to open it.

**Comment by equivalentideas** [comment]
For the design, I think just default text with blue links. It's simple and clear, lots of big organisations with successful fundraising do that for their emails and we had a good response on the survey email to PlanningAlerts users with that. I think that also suits the straight-forward character of OAF much more than the previous donations email to PlanningAlerts users.

If that's markedly less successful that last year we could try using the old or a new template later in the month for the second email.

@henare @mlandauer @kat are happy to go that way? Any ideas/questions etc. ?

Here's the 2013 PlanningAlerts email (las one sent):

![screen shot 2015-06-10 at 2 00 05 pm](https://cloud.githubusercontent.com/assets/1239550/8075304/3762b3e4-0f82-11e5-8c8c-763d0199283c.png)

January survey request email:
![screen shot 2015-06-10 at 2 57 36 pm](https://cloud.githubusercontent.com/assets/1239550/8075309/48382802-0f82-11e5-943f-494f1ef08fbb.png)

**Comment by henare** [comment]
>We'll need to important the latest subscribers from the different projects into civi. It would be good to start with PlanningAlerts as that's the first email we've got prepared. @henare could I rope you in to help with that?

I was going to document the process here but you're on to it.

>are happy to go that way? Any ideas/questions etc. ?

SGTM.

**Comment by equivalentideas** [comment]
I'm thinking this email actually comes from contact@planningalerts because if they're a keen PlanningAlerts user they'll recognise and jump on that address.

**Comment by equivalentideas** [comment]
After a fairly slow arvo post blog post I've got text drafts for the two emails :snail: . Unfortunately these'll have to go out Tuesday morning, as there's a few things to do before they can go:

* [ ] sign off Right To Know email text
* [ ] sign off generic email text
* [ ] update civic contacts with all the new users from Right To Know, They Vote For You, OpenAustralia Foundation, Election Leaflets and morph.io
* [ ] set up the emails to exclude the right users (e.g. don't send anything to PlanningAlerts, don't send generic one to Right To Know users either)

**Comment by equivalentideas** [comment]
Seeing the donations continue to come in, I'd like to send a follow up email to PlanningAlerts users who haven't donated. I meant to do this earlier, but everything else just took so long before I went away I forgot about this.

I think one more directly focused on the end of financial year last minute donors, short and to the point. Also explaining that there's no donation too small, it's all helpful to the project you love:

> Hi! I’m Matthew Landauer. I’m a director and founder of the OpenAustralia Foundation, the charity that runs PlanningAlerts.
> 
> We run PlanningAlerts as a free service because we believe you should be informed and have a say on changes to you local area. We can do this because of donations we receive from the people who use it, like you. This is the last time we'll ask for your help this year.
> 
> Every small donation makes a difference for us. Everything goes back into our projects to give you better information and easy ways to have your say. Donations over $2 are tax deductible.
> 
> [**If PlanningAlerts is useful to you, please take a moment to support it with a tax deductible donation this financial year.**]()
> 
> http://oaf.org.au/donate/planningalerts
> 
> Thank you for your support

@henare @mlandauer @kat could I get some quick feedback on this wording and any changes you think are appropriate, and then I can load this and send it out immediately—I don't think it's worth waiting for the morning as there's no too long before eofy and people might be doing tax stuff/checking out donations at any time.

I say the 'This is the last time we'll ask for your help this year.' in an email from wikimedia, and I think it's a nice touch, it's frank that these emails are a bit annoying some times. I think that fit's OAF's character. Also it's saying "we're not gonna remind you again, if you wanna do this, nows the moment".

**Comment by henare** [comment]
I really like the "This is the last time we'll ask for your help this year." (should that be financial year? probably not?) so my only feedback would be to see if we can front-load that concept more. It takes a while to get to that so if you've already read a similar email from us a couple of weeks ago and don't want to donate it might be very annoying.

**Comment by equivalentideas** [comment]
Thanks for that @henare What about in the subject even:

> Last chance to support PlanningAlerts this financial year

**Comment by mlandauer** [comment]
I think it's good. I agree with @henare - put the "this is the last time..." near to the front.

Also, I think it should include something that refers to the previous email almost as if it's a personal email.

Maybe something along the lines of "I emailed you a couple of weeks ago asking for your support. I realise you're busy..."

**Comment by henare** [comment]
:+1: on all counts.

**Comment by equivalentideas** [comment]
Thanks @mlandauer What about combining those ideas in a second par:

> Hi! I’m Matthew Landauer. I’m a director and founder of the OpenAustralia Foundation, the charity that runs PlanningAlerts.
> 
> I emailed you a couple of weeks ago asking for your support and hundreds of people have donated since then. I realise you're busy so this is the last time we'll ask for your help this year.
> 
> We run PlanningAlerts as a free service because we believe you should be informed and have a say on changes to you local area. We can do this because of donations we receive from the people who use it, like you.

**Comment by mlandauer** [comment]
Perfect!

**Comment by equivalentideas** [comment]
Nice. I'll send send this out now with the subject above.

**Comment by equivalentideas** [comment]
I'll send it to PlanningAlerts users and exclude recent donors so we don't annoy them.

**Comment by equivalentideas** [comment]
This is done. It was more successful than previous years. We received around $10k in donations following these emails in June. The last email to PlanningAlerts users, just before July, prompted over $5k alone.
