### ISSUE TITLE
Can't donate $25 regularly

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#209]
When trying to sign up for $25 monthly donation, I hit donate, it says processing, then I get:

![screen shot 2015-06-05 at 6 19 51 pm](https://cloud.githubusercontent.com/assets/1239550/8002135/aedbadf8-0baf-11e5-888b-62b4b8b0c260.png)

**Comment by equivalentideas** [comment]
Hmmm. I can see the errored request in our stripe logs, but I really thought that stripe would create a plan automatically for us if we hit it with a request. Did we manually create the $60 and $2 plans that are currently listed in Stripe? I can't see anything saying they would make them automatically in the Stripe docs and there's no mention of this in their api changelog since someone started a $60/month donation.

@henare any thoughts on what this could be?

If we have to pre-make plans, we can't really have a 'set your own amount' option for monthly donations. We could set up plans in Stripe for the listed payment amounts and remove the 'other' field if they check the 'monthly' box?

**Comment by henare** [comment]
>Did we manually create the $60 and $2 plans that are currently listed in Stripe?

No.

>I can't see anything saying they would make them automatically in the Stripe docs and there's no mention of this in their api changelog since someone started a $60/month donation.

IIRC the CiviCRM payment processor creates these "plans".

>@henare any thoughts on what this could be?

No, I don't know why it's not working.

**Comment by equivalentideas** [comment]
Ok, so I've just successfully signed up for a $10/month donation. I'll test a custom amount.

**Comment by equivalentideas** [comment]
$5 works two. Let's try manually adding $25 and see if that plugs the problem and then we can see if the issue reoccurs.

**Comment by equivalentideas** [comment]
We've manually added the plan and now I've successfully made a donation. I'll close this, reopen if the issue reoccurs.
