### ISSUE TITLE
Offer option of donating via Paypal

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/oaf#212]
The occasional person asks for it because they don't want to use their credit card on the internet. So, we should offer it as a backup option I think

**Comment by henare** [comment]
Here's a link people can use to pay via PayPal: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TKNGQF58E2UAN

**Comment by henare** [comment]
I've added this to the donate form: https://www.openaustraliafoundation.org.au/donate/
