### ISSUE TITLE
include how to pay on planningalerts landing page

### ISSUE THREAD

**Issue by kat** [openaustralia/oaf#213]
Include brief description of how people can donate on the first donate page -https://www.planningalerts.org.au/donate ie. credit card.

(A planningalerts user called me today. She wasn't clear about how she could make a donation. That said it's the first time anyone has done that!)

**Comment by henare** [comment]
We should also mention PayPal and add a link to it. That would fix #212 as well.

**Comment by henare** [comment]
I've included a sentence here: https://www.openaustraliafoundation.org.au/donate/planningalerts/

Feel free to reopen if you think we need it on the planningalerts.org.au page too.
