### ISSUE TITLE
Update email text to send to PlanningAlerts users

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#219]
Last year we send an email in early June and then one on the 29th.

The 29th email was by far the most successful. We’d like to repeat this combo.

We need to:

* [x] update the achievements for this year that we name in the email
* [x] change the sender to Henare
* [x] change call to action to say something like “tax-deductible one-off donation or become a regular supporter” ?

**Comment by kat** [comment]
Do we want to talk about 
*  how many more people we're reaching - 60% more people getting alerts
*  things users have done (like help save a historic pub)
*  writing to councillors
*  ??

**Comment by kat** [comment]
text of the email drafting [here](https://docs.google.com/document/d/1-f588iFjzWoEnKvF6s40PL5FxEavEgt0Bg2J-tv-78Y/edit)

**Comment by kat** [comment]
Have kept changes simple, above all to keep it short and to the point. Haven't included example actions because that's potentially offputting for some  @equivalentideas please have a look.

**Comment by kat** [comment]
first pass done at https://docs.google.com/document/d/1-f588iFjzWoEnKvF6s40PL5FxEavEgt0Bg2J-tv-78Y/edit

**Comment by equivalentideas** [comment]
I've done a iteration of this @kat https://docs.google.com/document/d/1-f588iFjzWoEnKvF6s40PL5FxEavEgt0Bg2J-tv-78Y/edit

I'm pretty happy to go with that for the first PlanningAlerts email, starting with the test on Wednesday #224 . Any more improvements/ simplifications that are helpful you think?

**Comment by kat** [comment]
Good to go @equivalentideas
