### ISSUE TITLE
Send final PlanningAlerts donations email

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#227]
<del>This goes out 29th June same as last year’s successful email</del>

> I think we move this back a day to the 28th to give people a little more time if they are thinking about tax.

**Comment by equivalentideas** [comment]
Because last year’s [late June email to PlanningAlerts users](https://github.com/openaustralia/oaf/issues/208#issuecomment-116365750) was so successful, I think we try and recreate it with as few tweaks as possible.

**It was sent to PlanningAlerts users who had not donated in the last 3 months**.

On the 29th. I think we move this back a day to give people a little more time if they are thinking about tax.

I've done a simple update of last years email in here. It's totally focused on a reminder and the financial year angle so nothing really needed updating.

https://docs.google.com/document/d/1-O0DpLXUz7G43LZmdQSqoWc4VHVXIxudr1EX1b3HDxI/edit

**Comment by equivalentideas** [comment]
#238 must be fixed before we send this out.

**Comment by equivalentideas** [comment]
See note on unsubscribe link in #238 :

> Please remember if you're sending a new email that the href of the unsubscribe link SHOULD BE {action.optOutUrl}, NOT {action.unsubscribeUrl}

**Comment by equivalentideas** [comment]
I've got [the text](https://docs.google.com/document/d/1-O0DpLXUz7G43LZmdQSqoWc4VHVXIxudr1EX1b3HDxI/edit) loaded in with the proper unsubscribe link.

I won't schedule this until we're made sure it wont go to people who've unsubscribed #238 .

**Comment by equivalentideas** [comment]
> I won't schedule this until we're made sure it wont go to people who've unsubscribed #238 .

Thats done 🎆 

I'm gonna send a test email and get another paid of :eyes: over the email this week for typos etc. before we schedule it.

**Comment by equivalentideas** [comment]
Looks good to me. Could you please cast an eye of the test email @henare and let me know when you have?

**Comment by henare** [comment]
Great stuff, @equivalentideas looks good. I've made a small suggestion on the text (in Docs) about thanking the people that have donated. It's nice to do and may motivate people to feel similarly thanked and make a donation. If you don't think we should put that in that's OK with me too.

**Comment by equivalentideas** [comment]
Thanks @henare . I like the thanks, even through this isn't going to people who've donated.

> It's nice to do and may motivate people to feel similarly thanked and make a donation.

In reenforces how much we appreciate it. I like it.

I'm gonna make that change (but use a proper em dash not a hyphen ;-) ).

Then I'll schedule the email to go out on Tuesday morning.

**Comment by equivalentideas** [comment]
I’ve scheduled this. It’ll go out next Tuesday the 28th at 11am. I’ve put it in the OpenAustralia Foundation calendar with a couple of reminders before hand.

**Comment by henare** [comment]
>but use a proper em dash not a hyphen
:fire: 

>I’ve scheduled this.
:tada:

**Comment by equivalentideas** [comment]
This went out.
