### ISSUE TITLE
Send Right To Know donations email

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#228]
This should go out on Tuesday 7th June or the next day, after #235 .

**Comment by equivalentideas** [comment]
This is running a bit late now.

Here's draft text to go out https://docs.google.com/document/d/14tRmsPg7DE9WEXwmqv97dZ1Eq2CTFwGmoj5XqhcKX-c/edit#

**Comment by henare** [comment]
This was sent today to 1,448 people.
