### ISSUE TITLE
Send donations drive email to general users

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#229]
Non PlanningAlerts and Right To Know users after test review #235.

This should go out on Tuesday 7th June or the next day.

**Comment by henare** [comment]
Draft email https://docs.google.com/document/d/1anNOT6ZKpC8XBALNjCbfs8Seb3YZZ_Uwr_hn10AILew/edit

**Comment by equivalentideas** [comment]
The email text and subject is now sorted. I'll send this out in the morning.

**Comment by equivalentideas** [comment]
Just sent this.
