### ISSUE TITLE
The branding of the stripe donation receipt is inconsistent with the donation website

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#232]
The donation receipt generated by stripe is bright blue and does not match the branding of the oaf website. This made the person I tested it with question the legitimacy of the org and whether it really was tax deductible etc.

Donation page on OAF:
![screen shot 2016-05-19 at 3 59 54 pm](https://cloud.githubusercontent.com/assets/1239550/15384097/47693fde-1ddb-11e6-884e-51fa2693cee0.png)

Receipt:
![screen shot 2016-05-19 at 3 55 54 pm](https://cloud.githubusercontent.com/assets/1239550/15384098/476adcf4-1ddb-11e6-82c3-0e49bd0dbb4f.png)

**Comment by jamezpolley** [comment]
Donorbox receipts are more close to the website.
