### ISSUE TITLE
Don't ask for donations from people who've unsubscribed from our projects

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#236]
Currently we keep people’s emails in civicrm until they unsubscribe there, even if they've unsubscribed from the project they used, e.g. PlanningAlerts. Does this make sense? These people are probably extremely unlikely to donate—though they did sign up to our projects so may well be interested in news from us. I'm not sure what the best thing is.

**Comment by henare** [comment]
I don't think that people that have unsubscribed should get emails from us.

**Comment by jamezpolley** [comment]
We did that this year.
