### ISSUE TITLE
Allow people to enter a message when they donate

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#239]
When people donate via PayPal they can enter a message that gets sent to us. They often use this to send us nice messages. Maybe we should do the same on our donation form?

**Comment by equivalentideas** [comment]
This is a very nice idea. [Bandcamp](https://bandcamp.com/) has this feature: when you buy music, you can write a short message to the artist. I really like that and always write something nice and thanks them. Makes me feel good, and I'm sure it's nice for them (based on our feelings about getting messages).

**Comment by jamezpolley** [comment]
Donorbox does this.
