### ISSUE TITLE
Review 2016 EOFY donations drive and changes we made to the form

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#240]
Was this a success?

Where the changes we made to the form (monthly by default and changes to suggested amounts) positive changes?

Any more issues arising?

**Comment by equivalentideas** [comment]
> Where the changes we made to the form (monthly by default and changes to suggested amounts) positive changes?

We decided to roll these back because quite a few people had accidentally signed up for recurring donations, and it was a pain for users, a pain for us and just felt wrong. I've made the changes to default to one-off instead of monthly payments.

**Comment by jamezpolley** [comment]
This information has informed our plans for 2019, but I'm going to close this issue as it's pretty stale now.
