### ISSUE TITLE
Work on email as a team (or teams of 2) at a regular time

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#241]
We get a bunch of email that's just addressed to either one of the contact@project emails or the generic @oaf one. It's everyone's responsibility to pick this up. It's really easy for stuff to slip by, or to hang around in the back of our minds because we have heaps of other generally more important stuff on. The multitasking involved in picking up bits of email gets us all down.

Rather than people picking this up individually, today @henare and I worked through some of our outstanding email together. We found it to be really positive and fairly quick. We immediately discussed anything that was tricky and responded 💯 

It made us think that it might be worth making this a regular weekly thing to make email easier, more fun, and the share the load.

**Comment by jamezpolley** [comment]
I like this as a general idea, but it's not practical at the moment and there's nothing actionable here, so I'm going to close this.
