### ISSUE TITLE
Split AdWords ad groups in campaign "OpenAustralia Foundation Projects" into separate campaigns

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#248]
As part of Amire's SEM audit they suggested we create quite granular Campaigns, i.e. at the project level or even specific campaigns within each project.

We currently have a catch-all "OpenAustralia Foundation Projects" campaign that contains ad groups about a number of our different projects. We need to split these into separate campaigns.

A number of these ad groups are performing well. What's stopped us from doing this is a worry that we'll lose that good work and historical data.

After speaking with Megan she advised that our goal is to pause this campaign, not remove it. So we won't really lose the historical data if we want it. However she also said the historical data isn't really that useful - you're focussed on the future with AdWords and making things perform better in the future is always the goal.

To move the ad groups into their own campaign Megan recommends using AdWords Editor to export the ad groups and reimport them back into their own campaigns. We were worried that we'd lose the performance of the ads if we did this. She advises that it doesn't matter too much - getting the account in order is more important. At worst it may take them 3 weeks to recover, probably a lot sooner since Google will notice they have exactly the same settings and rank them accordingly.

**Comment by equivalentideas** [comment]
I exported our existing account data on Friday, and I've put it up in Google Drive in case we need to access it https://drive.google.com/drive/u/0/folders/0B_0JrLy9bmIPUE9PZFMxNkNTZTg

**Comment by equivalentideas** [comment]
We've split this big campaign into separate campaigns for each of our projects. We've kept the original campaign as well and just paused it, so all the data on it is still available if we want it.

**Comment by equivalentideas** [comment]
We're now removing all of the MP name keywords/adgroups off our OpenAustralia Foundation campaign. These weren't performing well (probably because the ad copy and url aren't relevant to search). When we want to add these back in we can do it properly with custom ad copy and link directly to the MPs page.
