### ISSUE TITLE
FAQ Needs minor updates

### ISSUE THREAD

**Issue by alisonkeen** [openaustralia/oaf#250]
From the FAQ: 

**What is RSS?**
RSS files contain information about a list of things: diary entries, speeches, etc. and are formatted to be readable by computer programs, rather than humans. So what use are they? You can use a program called a news reader to store the locations of RSS feeds, and each time one is updated - with new diary entries or speeches - you can easily see what's new. It saves you visiting web pages on the off-chance anything new has appeared. Popular RSS readers are Sharpreader for Windows or NetNewsWire Lite for Macs. Bloglines and Google Reader are online RSS readers.

http://www.openaustralia.org.au/help/

Possible amendment: 

Maybe replace last sentence with "Some RSS readers include NetNewsWire for Apple, MS Outlook for Windows, Mozilla Thunderbird, and FlipBoard."

Also is Google Analytics still being used?

**Comment by alisonkeen** [comment]
I don't think I have permissions to tag this "low priority", I can't edit issue labels. (is this even in the right issues repo?)

**Comment by henare** [comment]
@alisonkeen thanks for logging this! The repository organisation is definitely a bit confusing. We use this for ones about the Foundation, not the project OpenAustralia.org. Can you please open this over at https://github.com/openaustralia/openaustralia/issues ?

**Comment by alisonkeen** [comment]
Oops, thankyou!
