### ISSUE TITLE
If you don't select an amount when donating it silently defaults to $15

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#256]
I observed this using a test-drive form. Looking at the code seems to confirm that would be the case when donating on a live form too:

![selection_002](https://cloud.githubusercontent.com/assets/48945/24182586/f6d1d968-0f16-11e7-8ddc-4dcea54c9fc1.png)

**Comment by equivalentideas** [comment]
@henare does the test mode include all the scripts/css that users see? A test mode I saw earlier didn't so wondering if that's the issue.

**Comment by henare** [comment]
Yes it does.

**Comment by equivalentideas** [comment]
> Yes it does.

Ah awesome. That's also a way better test page, than a hokey one I saw inside civicrm 👍 

I think a solution to this could be running a function we have to clear the buttons on page load. From memory it currently runs when you change the selection—and when we moved to default to 'once-off' I probably forgot to catch this situation.

**Comment by jamezpolley** [comment]
We don't use CiviCRM any more
