### ISSUE TITLE
Calculate volunteer numbers for 2016/2017 for reporting purposes

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/oaf#262]
Going to use the same method as #251 and #216. We're interested in the period Jul 1, 2016 – Jun 30, 2017

* everyone who's put in a request at righttoknow
* everyone who's uploaded an election leaflet
* code contributors to all projects 
* hackfest participants

Small potential additions:
* People who've posted to the morph.io forum
* People who have created issues on github / commented on them
* Contributors to planningalerts scrapers

**Comment by mlandauer** [comment]
> everyone who's put in a request at righttoknow
```
deploy@kedumba://srv/www/www.righttoknow.org.au/current$ rvm use ruby-2.0.0-p353
deploy@kedumba://srv/www/www.righttoknow.org.au/current$ bundle exec rails c production
2.0.0-p353 :002 > InfoRequest.where("created_at >= ? AND created_at < ?", "2016-07-01", "2017-07-01").collect { |i| i.user }.uniq.count
 => 622
```

The answer is 622 for the 2016/2017 financial year

**Comment by mlandauer** [comment]
Also going to check through the blog whether there were any events during that time that I might have missed here:
* Adding local councillors: https://www.openaustraliafoundation.org.au/2016/07/13/adding-your-local-councillors-to-planningalerts/
* FOI workshop: https://www.openaustraliafoundation.org.au/2016/11/24/theres-no-better-way-to-learn-how-easy-foi-requests-are-than-to-make-one/

There's also people who come to meetups during the year.

**Comment by mlandauer** [comment]
The spreadsheet of local councillor info is editable anonymously so I think it's not possible to figure out how many people helped out there unfortunately. With the FOI workshop it's hard to say who might have been a contributor. Since people were making FOI requests it's probably more reliable to just count the people there.

**Comment by mlandauer** [comment]
Since I'm relatively short of time I won't try to include some of the other suggestions. So, the total is `622 + 42` which comes to 664.

**Comment by mlandauer** [comment]
If we include the current number of members on our meetup group (648), the total comes to 1312.

**Comment by katska** [comment]
How do we make this easier to find next time we report? I'm including ACNC  and AIS in the title

**Comment by katska** [comment]
where ACNC is the Australian Charities and Non-for-Profits Commission and AIS is the Annual Information Statement.

**Comment by jamezpolley** [comment]
> Contributors to planningalerts scrapers

I'd like to see a time estimate on this one, at least. From what I've heard from @lovemydata I believe the average small fix to a scraper takes 4-6 hours, which is a pretty substantial donation.

**Comment by jamezpolley** [comment]
I've documented this at https://github.com/openaustralia/oaf/wiki/Calculating-Volunteer-numbers-for-ACNC-reports

**Comment by LoveMyData** [comment]
> > Contributors to planningalerts scrapers
> 
> I'd like to see a time estimate on this one, at least. From what I've heard from @LoveMyData I believe the average small fix to a scraper takes 4-6 hours, which is a pretty substantial donation.

Pretty hard to measure, some scraper took couple hours and like the recent SA Planning Portal, easily 6 hours due to rewrite from php to ruby and the web site also slightly changed.
