### ISSUE TITLE
PayPal Error on Donation Pages - Not Able to receive money

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/oaf#264]
https://www.openaustraliafoundation.org.au/donate/righttoknow/

Also on https://www.oaf.org.au/donate/

When you click the PayPal Link it says that we aren't setup to receive money.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hqjh)

**Comment by jamezpolley** [comment]
Connects to openaustralia/oaf-internal/issues/15

**Comment by jamezpolley** [comment]
We've decided not to bother with PayPal; it takes too much management time and effort.
