### ISSUE TITLE
Look for a replacement email campaign platform

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/oaf#269]
We currently have a self-hosted CiviCRM on Wordpress instance which we use to handle the mailouts for the annual EOFY donations drive. We have about 90k addresses in two main categories - PlanningAlerts and Everyone Else. We also use it to manage recurring and one-off donations via Stripe (but this issues is focused on the mailing list use). 

We've had a history of issues with CiviCRM - eg, unsubscribes/opt-outs not working as expected (#24, #177, #238, probably others) (also many issues with stripe integration, but that isn't the focus here). It seems likely that some of these problems are things we could work around if we knew more about how to use CiviCRM (eg, #238 seems to have mostly been a lack of experience with CiviCRM), while some others are bugs that would be solved if we could upgrade CiviCRM. 

However: upgrading CiviCRM involves upgrading the underlying OS and switching to php7; and then continual maintenance and upgrades; and it wouldn't solve the experience gap.

The upgrades are within our technical capabilities, and the experience gap could be fixed - but none of this would help advance the Foundation's core goals. At the moment, time is the most scarce resource we have, and this would consume a lot of time.

So - let's consider alternatives.

Our requirements are:

- Need to be able to handle ~100k email addresses, split into at least two sub-groups (PlanningAlerts and Everyone Else).
- Needs to have simple ways for recipients to opt-out of all future mass mailouts (if they're subscribed to OpenAustralia.org alerts, planningalerts.org alerts etc we wouldn't expect those to be affected)
- Needs to have minimal expertise from us - it needs to save us time compared with upgrading and learning to use CiviCRM
 - Our budget is tight; our current CiviCRM hosting is costing us <$100/month. It's worth spending more to get a solution that isn't going to consume our time, but we need to be balance spending on this with spending on advancing our mission.

Nice to have (this list is a braindump and probably contains ideas that will be rejected as not the kind of marketing we want to do):
- Conversion/clickthrough tracking?
- Ability to do A/B testing by sending variant emails to subsets of the lists
- Ability to schedule future messages
- Some way to send a different followup message to people who have already responded during this drive.
- Ability to vary messages based on known data about the recipient - eg, perhaps we could show people some PlanningAlerts from their region, if we know what areas they're looking at on PlanningAlerts.

**Comment by jamezpolley** [comment]
CampaignMonitor looks great, but only scales to 50,000 list members before we'd have to ask for custom pricing. I've fired off a request for custom pricing, but got an error message - "We are sorry. Our servers are busy and we are not able to submit your request at this time.". Support only seems to be available on a US phone number. At 50,000 list members we're already looking at 460.90USD/month.

**Comment by jamezpolley** [comment]
I haven't looked into MailChimp as deeply yet. Their "Standard" plan scales to 100,000 subscribers for USD499/month; "Mailchimp offers a 15% discount to nonprofits and charities." which should bring that down a little. That still makes it close to $6k/year.

**Comment by jamezpolley** [comment]
Another option would be continuing to self-host CiviCRM, but get support to get it configured and maintained. I've spoken to AgileWare to get a quote for rough costings for this option. Because of the volume of subscribers we have, their suggestion is that we provide an m5.large instance and allow them access for support and maintenance.

Costing for this option:
$680 for 1 m5.large instance for 12 months
$600 - initial setup of latest CiviCRM, including (I think, verifying) a "Members area" where the list members could manage their details (email address, home address, subscription options etc)
Either $200/month or $350/month for 4/8 hours support, including civicrm updates.
Optionally: $600 for AgileWare to also handle the initial OS and Wordpress setup, or we can do that ourselves.

Min cost: $3680 over 12 months, including AWS hosting; $4580 if we have 8 hours of support for the first 6 months and then drop to 4 hours once things are stable. Subsequent years - $1200 (assuming 4 hours of support remains enough) + $680 for AWS.

**Comment by jamezpolley** [comment]
We've decided to go ahead with CampaignMonitor. Further work on EOFY2019 tracked in https://github.com/openaustralia/oaf/issues/272

**Comment by jamezpolley** [comment]
Another option would be continuing to self-host CiviCRM, but get support to get it configured and maintained. I've spoken to an australian host to get a quote for rough costings for this option. Because of the volume of subscribers we have, their suggestion is that we provide an m5.large instance and allow them access for support and maintenance.

Costing for this option are available in https://github.com/openaustralia/oaf-internal/issues/66.

**Comment by dptarrant** [comment]
James, I might be able to help.  If you want to take this off line you can contact me at dtarrant@nubay.org
