### ISSUE TITLE
Update contact address for Elasticsearch

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/oaf#291]
Emails say that we can "Customize who receives billing emails in your organization by[ updating your email settings](https://cloud.elastic.co/account/profile)."

Matthew, the emails are going to you, so I think it needs to be you who logs in to change this.

Required by #285

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wog5)

**Comment by mlandauer** [comment]
I've updated the "operational contact" to contact@oaf.org.au and the "billing contact" to accounts@oaf.org.au.

Sorry it took me so long to fix this!
