### ISSUE TITLE
Get delivery information out of cuttlefish? If so see what we did last year at https://github.com/openaustralia/oaf/issues/278

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/oaf#301]

**Comment by jamezpolley** [comment]
I've run the same query as in #278 and the results are in deliveries.csv.

Anything that's in that file with 'hard_bounce' as the status should be added to our blacklist  before we do a mailout to reduce the number of bounces we get - too high an error rate is a signal that we've got a poor quality list

**Comment by jamezpolley** [comment]
3970 addresses in the hard_bounce state, about 2/3 of which were already on the campaignmonitor suppression list, which means they've been hard bouncing for >12 months..

**Comment by mlandauer** [comment]
> I've run the same query as in #278 and the results are in deliveries.csv.
Thanks. Where is `deliveries.csv`?
