### ISSUE TITLE
AWS EC2 Reserved Instances expired in May.

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/oaf#324]
Our EC2 reservations ran out 2020-05-15T00:45:31.000Z and 2020-05-19T06:13:33.000Z.

We had reservations for a total of 50RIs in ap-southeast-2 and they were covering around 80% of our workload in the 3 months to May 15.

Cost Comparisons:
Apr 15-May 15: 78% coverage, $166.68 of RI gave us $266.22 on-demand-equivalent resources, saving $99.54. We paid $41.89 for the remaining 22%. 166.68+40.89=208.57 total cost.

May 20-Jun 20 - we paid $342.56

Current reccomendation is to by 55RIs in ap-southeast-2. Upfront cost of $2200, we'd save an estimated 44.21/month.
If we commit to 3 years at this level of usage, we'd pay $4455 upfront and expect to save 103.79/month (41%)

**Comment by katska** [comment]
@mlandauer shall we do it?

**Comment by jamezpolley** [comment]
The risk with purchasing the RIs is that if our usage goes down - or if we shift our usage out of ap-southeast-2 - we won't use the reserved capacity.

To me, the risk across the next 12 months seems low; we don't expect to be decreasing the things we do over the next 12 months. The risk across the next 3 years is higher.

My reccomendation is that we go with the 55RIs for 12 months, same as last year.

**Comment by katska** [comment]
sounds good to me

**Comment by mlandauer** [comment]
Okay cool. Thanks for the recommendation @jamezpolley. Done that. That comes to $2200 USD.
