### ISSUE TITLE
Calculate Volunteer Numbers for 2020/21 for ACNC reporting

### ISSUE THREAD

**Issue by katska** [openaustralia/oaf#338]
Last done in #326 for 2019/20
Before that - #262 #268, #299
https://github.com/openaustralia/oaf/wiki/Calculating-Volunteer-numbers-for-ACNC-reports

### RightToKnow:

| Year | Unique Users | Requests |
| --- | --- | --- |
| 17/18 | 346 | 977 |
| 18/19 | 317 | 816 |
| 19/20 | 462 | 957 |
| 20/21 | 405 | 1099 | 

### Code contributors

Total - 20/21
```
      6 Ben Fairles
      1 Ben Fairless
      2 Billy Kwong
      1 dependabot[bot]
     11 James Polley
      4 katska
     20 mackaymackay
    919 Matthew Landauer
```

### PlanningAlerts Scraper contributors
```      1 Daniel Hoolihan
     15 James Polley
    500 Matthew Landauer
      1 Michael Bone
     27 muzza1976```

**Comment by jamezpolley** [comment]
I'm not sure what's happening here. From the wiki page:
```
2.0.0-p353 :002 > InfoRequest.where("created_at >= ? AND created_at < ?", "2017-07-01", "2018-07-01").collect { |i| i.user }.uniq.count
 => 622
```

But when I do the same thing today:
```
irb(main):001:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2017-07-01", "2018-07-01").collect { |i| i.user }.uniq.count
=> 346
```

I'm not sure if that indicates I'm doing something wrong, or if we've done something to weed out inactive users.

... ah - comment on https://github.com/openaustralia/oaf/issues/268#issuecomment-476059993 suggests that the 662 number was actually for the 16/17 period, so presumabbly I've used the wrong dates when I created the sample commands in the wiki page. 346 does match the 17/18 period according to that comment. Very good. Moving forward!

```
irb(main):001:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2017-07-01", "2018-07-01").collect { |i| i.user }.uniq.count
=> 346
irb(main):002:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2018-07-01", "2019-07-01").collect { |i| i.user }.uniq.count
=> 317
irb(main):003:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2019-07-01", "2020-07-01").collect { |i| i.user }.uniq.count
=> 462
irb(main):004:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2020-07-01", "2021-07-01").collect { |i| i.user }.uniq.count
=> 405
irb(main):005:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2017-07-01", "2018-07-01").count
=> 977
irb(main):006:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2018-07-01", "2019-07-01").count
=> 816
irb(main):007:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2019-07-01", "2020-07-01").count
=> 957
irb(main):008:0> InfoRequest.where("created_at >= ? AND created_at < ?", "2020-07-01", "2021-07-01").count
=> 1099
```

**Comment by jamezpolley** [comment]
Code Contributors

Total - 20/21
```
      6 Ben Fairles
      1 Ben Fairless
      2 Billy Kwong
      1 dependabot[bot]
     11 James Polley
      4 katska
     20 mackaymackay
    919 Matthew Landauer
```

**Comment by katska** [comment]
@jamezpolley sorry I'm just looking for a final number of volunteers as per the usual working out. 
Do you have a number or is this still in progress?

**Comment by katska** [comment]
@jamezpolley please can you confirm what the above means? I see names and numbers, but they don't seem to relate to the information as I've seen it before.

**Comment by katska** [comment]
If I take this literally it's that 8 unique people contributed to github across projects mentioned so far.

**Comment by mlandauer** [comment]
410 is the final answer
